# BDA Project

This is a sketch for the final python notebook that we are going to submit.

In [12]:
# here some code

import numpy as np
data = np.random.rand(10,4)

print(data)

[[0.83857273 0.3519234  0.09615382 0.68929281]
 [0.2051633  0.76087083 0.29103349 0.48448679]
 [0.37795997 0.25040213 0.82496983 0.1631473 ]
 [0.16173063 0.06677135 0.32245608 0.48476149]
 [0.81213632 0.26993057 0.07792519 0.72893685]
 [0.76432717 0.69715555 0.36580635 0.20512632]
 [0.71091257 0.87690831 0.48507067 0.95820359]
 [0.3891748  0.7642684  0.50882457 0.73995821]
 [0.29012064 0.0325037  0.53658147 0.69609708]
 [0.02914469 0.05953407 0.81886591 0.15415961]]
